### ISSUE TITLE
Extern type defined with generic parameters incorrectly generated in C++

### ISSUE THREAD

**Issue by Goos** [dropbox/djinni#149]
When defining an external type in yaml like so:

```yaml
name: generic_interface
typedef: 'interface'
params: [parameter]
prefix: ''
cpp:
  typename: 'test::GenericInterface'
  header: '"../generic_interface.hpp"'
  byValue: false
    
  # Followed by the java + obj-c definitions
```

And an interface using the type:
```
do_things(): generic_interface<another_type>;

```

The signature for a method using this type is generated thusly:

```c++
virtual std::shared_ptr<test::GenericInterface><AnotherType> doThings() = 0;
```

So the type parameter is tacked on at the end of the pointer definition, rather than after the type definition, as one would expect:

```c++
virtual std::shared_ptr<test::GenericInterface<AnotherType>> doThings() = 0;
```
